name: Deploy Angular to S3

on:
  push:
    branches:
      - main   # or master, adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use version Angular supports

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }}
          SOURCE_DIR: dist/note-taker-frontend
